# Site settings
title: Data Science at Home
header-img: img/home-bg.jpg
email: francesco.gadaleta@gmail.com
copyright_name: datascienceathome.com
description: "Stories and tips about data science for small and large enterprises, from wherever you are"
baseurl: ""
url: http://datascienceathome.com
twitter_username: thisisfrag
github_username:  worldofpiggy
facebook_username:  worldofpiggy
email_username:  francesco.gadaleta@gmail.com
author: Frag
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-37903879-3

disqus: fgadaleta

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-admin]
